# Generated by Django 3.2 on 2021-06-24 06:05

from django.db import migrations, models
import patientsview.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='uploads/images/patients/icon.png', upload_to=patientsview.models.upload_path)),
                ('patient_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('account_created_hospital_id', models.CharField(default='', max_length=100)),
                ('app_id', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(default='', max_length=250)),
                ('mobile_no', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('password_before_verification', models.CharField(max_length=255)),
                ('joined_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
