# Generated by Django 3.2 on 2021-06-25 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientsview', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientaccount',
            name='password_before_verification',
        ),
    ]
