# Generated by Django 3.2 on 2021-06-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsview', '0002_remove_patientaccount_password_before_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientaccount',
            old_name='verified',
            new_name='email_verified',
        ),
        migrations.RemoveField(
            model_name='patientaccount',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='aadhar_number',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='mobile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
