# Generated by Django 3.2 on 2021-06-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsview', '0003_auto_20210625_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientaccount',
            name='account_created_hospital_id',
            field=models.CharField(max_length=100),
        ),
    ]
