# Generated by Django 3.2 on 2021-06-30 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsview', '0004_alter_patientaccount_account_created_hospital_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=30)),
                ('doctor_id', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('revisit_date', models.DateField()),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verify_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PatientsTestFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=100)),
                ('app_id', models.CharField(max_length=30)),
                ('tested_files', models.FileField(upload_to='')),
                ('doctor_id', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('verify_token', models.CharField(max_length=255)),
                ('entered_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
