# Generated by Django 3.2 on 2021-07-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsview', '0005_patientshistory_patientstestfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientshistory',
            name='app_id',
        ),
        migrations.AddField(
            model_name='patientshistory',
            name='aadhar_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='patientshistory',
            name='symptoms',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patientshistory',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='patientshistory',
            name='verify_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
