# Generated by Django 3.2 on 2021-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientsview', '0007_alter_patientshistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='otp_code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
