# Generated by Django 3.2 on 2021-06-24 06:05

from django.db import migrations, models
import doctorsview.models


class Migration(migrations.Migration):

    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, default='uploads/images/doctors/icon.png', upload_to=doctorsview.models.upload_path)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('hospital_id', models.CharField(default='', max_length=100)),
                ('doctor_id', models.CharField(max_length=40, unique=True)),
                ('app_id', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(default='', max_length=150)),
                ('dept', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(default='', max_length=255)),
                ('email_Verified', models.BooleanField(default=False)),
                ('password_before_verification', models.CharField(max_length=255)),
                ('joined_date', models.DateField()),
                ('verify_token', models.CharField(default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
