# Generated by Django 3.2 on 2021-07-08 12:20

from django.db import migrations, models
import doctorsview.models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraccount',
            name='background',
            field=models.ImageField(blank=True, default='uploads/images/doctors/bg.jpg', upload_to=doctorsview.models.upload_path),
        ),
    ]
