# Generated by Django 3.2 on 2021-07-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorsview', '0002_doctoraccount_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraccount',
            name='fb_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='doctoraccount',
            name='insta_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='doctoraccount',
            name='tweet_url',
            field=models.URLField(default=''),
        ),
    ]
